// <auto-generated />
using System;
using EC.TaskBoard.Web.Features.Board.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EC.TaskBoard.Web.src.Features.Board.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BoardDbContext))]
    [Migration("20260223132709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EC.TaskBoard.Web.Features.Board.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(5);

                    b.Property<string>("Current")
                        .HasColumnType("text")
                        .HasColumnOrder(3);

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<string>("Previous")
                        .HasColumnType("text")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("EC.TaskBoard.Web.Features.Board.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(0)
                        .HasColumnType("text")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(5);

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(0)
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("ListId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("EC.TaskBoard.Web.Features.Board.Domain.Entities.List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(0)
                        .HasColumnType("text")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("List");
                });

            modelBuilder.Entity("EC.TaskBoard.Web.Features.Board.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("EC.TaskBoard.Web.Features.Board.Domain.Entities.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.ClientNoAction);
                });

            modelBuilder.Entity("EC.TaskBoard.Web.Features.Board.Domain.Entities.Card", b =>
                {
                    b.HasOne("EC.TaskBoard.Web.Features.Board.Domain.Entities.List", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
